spring:
  application:
    name: kill-team-discord-bot
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  docker:
    compose:
      lifecycle-management: start_only
      enabled: false
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

discord:
  bot:
    token: ${DISCORD_BOT_TOKEN}
  channel:
    id: ${DISCORD_CHANNEL_ID}
  oauth:
    url: ${DISCORD_OAUTH_URL}

pairing:
  strategy: least-played

poll:
  cron: ${POLL_INTERVAL}
  question: "Are you coming to play Kill Team this week on tuesday at 17:30?"
  duration: PT72H
